### ISSUE TITLE
TypeError: Cannot read property 'name' of null

### ISSUE THREAD

**Issue by rogierschouten** [artifacthealth/tsreflect-compiler#2]
```shell
$ node ./node_modules/tsreflect-compiler/lib/tsreflect-compiler.js ./lib/common/core/collections/Bag.ts

c:\Source\eXLent_master\exlent\node_modules\tsreflect-compiler\node_modules\doctrine\doctrine.js:1761
                    if (isParamTitle(this._title) && this._tag.type.name) {
                                                                   ^
TypeError: Cannot read property 'name' of null
    at TagParser.parseName (c:\Source\eXLent_master\exlent\node_modules\tsreflect-compiler\node_modules\doctrine\doctrine.js:1761:68)
    at TagParser.parse (c:\Source\eXLent_master\exlent\node_modules\tsreflect-compiler\node_modules\doctrine\doctrine.js:1976:34)
    at parseTag (c:\Source\eXLent_master\exlent\node_modules\tsreflect-compiler\node_modules\doctrine\doctrine.js:1999:27)
    at Object.parse (c:\Source\eXLent_master\exlent\node_modules\tsreflect-compiler\node_modules\doctrine\doctrine.js:2071:23)
    at getJsDocComment (c:\Source\eXLent_master\exlent\node_modules\tsreflect-compiler\lib\tsreflect-compiler.js:9305:48)
    at emitParameterProperties (c:\Source\eXLent_master\exlent\node_modules\tsreflect-compiler\lib\tsreflect-compiler.js:9721:40)
    at emitClassDeclaration (c:\Source\eXLent_master\exlent\node_modules\tsreflect-compiler\lib\tsreflect-compiler.js:9745:17)
    at emitNode (c:\Source\eXLent_master\exlent\node_modules\tsreflect-compiler\lib\tsreflect-compiler.js:10175:28)
    at emitLines (c:\Source\eXLent_master\exlent\node_modules\tsreflect-compiler\lib\tsreflect-compiler.js:9247:17)
    at emitSourceFile (c:\Source\eXLent_master\exlent\node_modules\tsreflect-compiler\lib\tsreflect-compiler.js:9469:13)
```

Input file:
```javascript
/// <reference path="../../../../typings/node/node.d.ts" />
"use strict";
class Bag<T> {
	/**
	 * Constructor
	 * @param (optional) a collection of initial values, must have a forEach()
	 */
	constructor(elements?: any) {
		if (elements) {
			elements.forEach((element: T): void => {
			// do nothing
			});
		}
	}
}

export = Bag;
```

**Comment by meirgottlieb** [comment]
The error is in doctrine, which is the lib that I use to parse JsDoc. It looks like the format for your optional parameter is incorrect. See http://usejsdoc.org/tags-param.html#optional-parameters-and-default-values. Per docs, here is the syntax for an optional param without a default value:

@param {any=} elements A collection of initial values, must have a forEach()

That said, I'll catch errors from doctrine and provide a better error message. Thanks.

**Comment by rogierschouten** [comment]
True, the comment is not what I had intended (I forgot the name). But is the type annotation also necessary? We use typedoc for documentation not javadoc and it infers the types from typescript. 

In general, I think it limits the usefulness of tsreflect to give errors on comments because there are multiple documentation tools around (yuidoc, typedoc, ...) with all slightly different syntax. 
Maybe turn into warnings?

**Comment by meirgottlieb** [comment]
I'd like a better error message from doctrine but it should be able to handle all those cases since they are all variants of JsDoc. For typedoc you can leave out the type and the optional indicator in the @param comment and it should work fine. Your original @param comment was missing the parameter name. Looks like that would be incorrect in typedoc as well. See below for correct syntax.

@param elements A collection of initial values, must have a forEach()

I'll put in a bug request with doctrine to provide a better error message if the name is missing and leave this bug open until that's fixed.

**Comment by meirgottlieb** [comment]
I created a comment parser based on Doctrine that gives more control over error reporting and allows for a looser interpretation of JsDoc comments. That said, a parameter name will still be required for the @param tag. Given your original @param tag, you would now get the following error:

error TS10011: Error parsing JsDoc comment on line 1 of comment: Missing or invalid param name.
